import Head from 'next/head'
import Grid from '@mui/material/Grid'; // Grid version 1

import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {altColorPalette, MyChart, pastelColorPalette, retroColorPalette} from '../components/chart';
import { useRouter } from 'next/router'

import Multiselect from 'multiselect-react-dropdown';


export default function Home() {
  const router = useRouter()
  let queryString = Object.keys(router.query).map(key => key + '=' + router.query[key]).join('&');
  if (queryString) {
    queryString = '?' + queryString;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
          <Grid item xs={6}>
            <MyChart title="Event Counts Over Time" endpoint={'/v1/trends/events' + queryString} />
          </Grid>
          <Grid item xs={6}>
            <MyChart title="State Averaged Over Time" endpoint={'/v1/trends/states' + queryString} />
          </Grid>
        </Grid>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
