import Head from 'next/head'
import Grid from '@mui/material/Grid'; // Grid version 1
import React from 'react';

import styles from '../styles/Home.module.css'
import {
  altColorPalette,
  MyChart,
} from '../components/chart';
import { useRouter } from 'next/router'
import {ParsedUrlQuery} from "querystring";

export default function Home() {
  const router = useRouter()

  let queryParams: ParsedUrlQuery = {...router.query}
  queryParams.network = queryParams.network || 'mainnet'

  let queryString = Object.keys(router.query).map(key => key + '=' + router.query[key]).join('&')
  if (queryString) {
    queryString = '?' + queryString
  }

  function stateQuery (state: string) {
    return Object.keys(queryParams).map(key => key + '=' + queryParams[key]).join('&') + '&state=' + state;
  }

  const altChartOptionsShuffle = () => {
    return [...altColorPalette].map(value => ({ value, sort: Math.random() }))
      .sort((a, b) => a.sort - b.sort)
      .map(({ value }) => value)
  }


  const states = ['totalSupply', 'globalRank', 'totalXenStaked', 'activeMinters', 'activeStakes', 'amp', 'eaar', 'apy'];
  const networks = [
    {
      color: altChartOptionsShuffle(),
      name: 'mainnet',
      title: 'Mainnet'
    },
    // {
    //   color: altChartOptionsShuffle(),
    //   name: 'goerli',
    //   title: 'Goerli'
    // },
    // {
    //   color: altChartOptionsShuffle(),
    //   name: 'polygon-mumbai',
    //   title: 'Polygon Mumbai'
    // },
    // {
    //   color: altChartOptionsShuffle(),
    //   name: 'bsc-testnet',
    //   title: 'BSC Testnet'
    // },
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>XEN Charts</h1>

      <main>
        <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} height={360}>
          <Grid item xs={12}>
            <MyChart title="Event Counts Over Time" endpoint={'/v1/trends/events' + queryString}/>
          </Grid>
        </Grid>

        {networks.map(network => (
          <React.Fragment key={network.name}>

          <h1>{network.title}</h1>

          <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} p={2}>
            {states.map(state => (
              <Grid item xs={12} sm={3} key={state}>
                <MyChart title={state} endpoint={'/v1/trends/states?' + stateQuery(state)}
                         colorPalette={network.color} />
              </Grid>
            ))}
          </Grid>
          </React.Fragment>
        ))}
      </main>
    </div>
  )
}
